<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
		<head>
			<title>XML Sitemap - PixelResize</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
			<style type="text/css">
				body {
					font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
					font-size: 14px;
					color: #333;
					margin: 0;
					background: #f4f7f6;
				}
				a {
					color: #4f46e5;
					text-decoration: none;
				}
				a:hover {
					text-decoration: underline;
				}
				.header {
					background: #fff;
					padding: 40px 20px;
					text-align: center;
					border-bottom: 1px solid #e1e4e8;
				}
				.header h1 {
					margin: 0;
					font-size: 24px;
					font-weight: 700;
					color: #111;
				}
				.header p {
					margin: 10px 0 0;
					color: #666;
				}
				.content {
					max-width: 900px;
					margin: 40px auto;
					padding: 0 20px;
				}
				table {
					width: 100%;
					background: #fff;
					border-collapse: collapse;
					border-radius: 8px;
					overflow: hidden;
					box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
				}
				th {
					background: #f8fafc;
					text-align: left;
					padding: 12px 15px;
					font-weight: 600;
					color: #475569;
					border-bottom: 1px solid #e2e8f0;
				}
				td {
					padding: 12px 15px;
					border-bottom: 1px solid #f1f5f9;
				}
				tr:last-child td {
					border-bottom: none;
				}
				.priority {
					font-weight: 600;
					color: #10b981;
				}
			</style>
		</head>
		<body>
			<div class="header">
				<h1>XML Sitemap</h1>
				<p>Generated by PixelResize to help search engines discover our free image tools.</p>
			</div>
			<div class="content">
				<table>
					<thead>
						<tr>
							<th>URL</th>
							<th>Priority</th>
							<th>Change Freq.</th>
							<th>Last Change</th>
						</tr>
					</thead>
					<tbody>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<tr>
								<td>
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<a href="{$itemURL}">
										<xsl:value-of select="sitemap:loc"/>
									</a>
								</td>
								<td>
									<span class="priority"><xsl:value-of select="sitemap:priority"/></span>
								</td>
								<td>
									<xsl:value-of select="sitemap:changefreq"/>
								</td>
								<td>
									<xsl:value-of select="sitemap:lastmod"/>
								</td>
							</tr>
						</xsl:for-each>
					</tbody>
				</table>
			</div>
		</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
